### PR TITLE
fix(build): KEX Algorithms were invalidly extracted

### LINKED ISSUE #37: [BUG] - KEX algorithms incorrectly extracted from `openssh-portable`
## Description

The list of KEX algorithms is incorrect: https://github.com/veeso/ssh2-config/blob/935839c65640999947999a16c2970ab3fb8d37be/src/default_algorithms/openssh.rs#L16

You are importing from `KEX_CLIENT`: https://github.com/veeso/ssh2-config/blob/935839c65640999947999a16c2970ab3fb8d37be/build/openssh.rs#L51

However, `KEX_CLIENT` is the prepared algorithms list-of-lists for use in the SSH protocol: https://github.com/openssh/openssh-portable/blob/a6f8f793d427a831be1b350741faa4f34066d55f/myproposal.h#L96

`KEX_CLIENT` contains prefilled fields for the data structure used for negotiation, [where each position corresponds to a different type of algorithm](https://www.rfc-editor.org/rfc/rfc4253#section-7.1) (KEX, host keys, ciphers, MACs, compression, languages; most with client-to-server and server-to-client variants). It does *not* contain the KEX algorithms!

The client-side KEX algorithms are defined in `KEX_CLIENT_KEX`: https://github.com/openssh/openssh-portable/blob/a6f8f793d427a831be1b350741faa4f34066d55f/myproposal.h#L37

## Additional information

If you look at the list under the "Key Exchange (KEX) algorithms" heading at https://github.com/veeso/ssh2-config/blob/935839c65640999947999a16c2970ab3fb8d37be/src/default_algorithms/openssh.rs#L16 carefully, then you will see:

1. That it contains lots of duplicates.
2. That it contains not only legitimate KEX algorithms (like `mlkem768x25519-sha256`, `curve25519-sha256`, and the various Diffie-Hellman variants – out of which only the client KEX algos, not the server KEX algos should be present), but also host key algorithms (like `ssh-ed25519-cert-v01@openssh.com` and `rsa-sha2-512`), encryption/cipher algorithms (like `chacha20-poly1305@openssh.com` and `aes128-ctr`, appearing twice), MAC algorithms (like `umac-64-etm@openssh.com` and `hmac-sha2-256`, also appearing twice), and compression algorithms (`none` and `zlib@openssh.com`, also appearing twice) - none of which are valid KEX algorithms.

## Proposed fix

Change line 51 in `build/openssh.rs` from `"KEX_CLIENT"` to `"KEX_CLIENT_KEX"`, matching the corresponding algorithm selection in `openssh-portable`: https://github.com/openssh/openssh-portable/blob/a6f8f793d427a831be1b350741faa4f34066d55f/readconf.c#L3020

Make sure to not only rebuild the defaults list, but also the corresponding documentation.

### PR DESCRIPTION
**Pull request by veeso**
# KEX Algorithms incorrectly extracted from `openssh-portable`

Also removed duplicated and invalid algorithms from the default list

closes #37

### CODE REVIEW

File: build/openssh.rs [hunk 1]
```diff
@@ -34,32 +35,32 @@ pub fn get_my_prefs() -> anyhow::Result<MyPrefs> {
...
     let host_key_algorithms = defines
         .get("KEX_DEFAULT_PK_ALG")
-        .map(split_algos)
+        .map(|s| get_algos_for(s, AlgoType::Pubkey))
         .unwrap_or_default();
 
     let kex_algorithms = defines
-        .get("KEX_CLIENT")
-        .map(split_algos)
+        .get("KEX_CLIENT_KEX")
```
Comment (LeoniePhiline) [inline build/openssh.rs]: @veeso 

**Changing `"KEX_CLIENT"` to `"KEX_CLIENT_KEX"` was the only change required to fix the incorrect algorithm extraction.**

The `get_algos_for` function, `AlgoType` and prefix check, and duplicates check are unnecessary:

The duplicates merely stemmed from `"KEX_CLIENT"`, which configures the same algorithms by default for server-to-client and client-to-server directions!

The prefix check is even a source of future bugs, since the addition of new algorithms upstream, which do not match your filters, would cause these new algorithms to incorrectly be excluded.

The prefix checks are also unnecessary because you aimed them at removing `"none"`, but `"none"` is a *compression* algorithm, which you previously extracted via the wrong `#define`: `"KEX_CLIENT"`. Once you extract from `"KEX_CLIENT_KEX"` instead, you will no longer see `"none"` or `"zlib@openssh.com"` in your list, and there is no need at all to filter the lists.
You can trust that `openssh-portable` contains only valid algorithm names, which you can import without prefix checks.

All issues you tried to fix with additional checks are fixed by extracting from the correct `#define`, and none of the additional checks are necessary at all.

**My recommendation:**

- First, revert **all** changes in this file.
- Then, **only** change `.get("KEX_CLIENT")` to `.get("KEX_CLIENT_KEX")`.
- Release as v0.6.6.
